INSERT INTO scenario (scenario_id, cluster_id, scenario_title, scenario_type, is_default)
VALUES (1, 'Zk_default_cluster_id_for_all_scenarios', 'Exception', 'SYSTEM', true);

INSERT INTO scenario (scenario_id, cluster_id, scenario_title, scenario_type, is_default)
VALUES (2, 'Zk_default_cluster_id_for_all_scenarios', '4xx Error', 'SYSTEM', true);

INSERT INTO scenario (scenario_id, cluster_id, scenario_title, scenario_type, is_default)
VALUES (3, 'Zk_default_cluster_id_for_all_scenarios', '5xx Error', 'SYSTEM', true);

INSERT INTO scenario (scenario_id, cluster_id, scenario_title, scenario_type, is_default)
VALUES (4, 'Zk_default_cluster_id_for_all_scenarios', 'Requests with latency > 100ms', 'SYSTEM', true);

INSERT INTO scenario_version (scenario_version_id, scenario_id, scenario_data, scenario_version, schema_version, created_by)
VALUES (1, 1, '{"version":"1684149787","scenario_title":"Exception","scenario_type":"SYSTEM","enabled":true,"workloads":{"5370c7dd-c83a-5952-9db2-42df1a4191b0":{"executor":"OTEL","service":"*/*","trace_role":"server","protocol":"HTTP","rule":{"type":"rule_group","condition":"AND","rules":[{"type":"rule","id":"\"attributes\".\"http.status_code\"","field":"Response Status","datatype":"","input":"","operator":"exists","value":""},{"type":"rule","id":"errors","field":"Error","datatype":"bool","input":"bool","operator":"exists","value":"true"}]}}},"scenario_id":"1","filter":{"type":"workload","condition":"AND","workload_ids":["5370c7dd-c83a-5952-9db2-42df1a4191b0"]},"group_by":[{"workload_id":"5370c7dd-c83a-5952-9db2-42df1a4191b0","title":"#getWorkloadFromIP(SourceIP)","hash":"#getWorkloadFromIP(SourceIP)"},{"workload_id":"5370c7dd-c83a-5952-9db2-42df1a4191b0","title":"error[0].message","hash":"error[0].message"}],"rate_limit":[{"bucket_max_size":5,"bucket_refill_size":5,"tick_duration":"1m"}]}', 1693843788, 'v1', 'SYSTEM');

INSERT INTO scenario_version (scenario_version_id, scenario_id, scenario_data, scenario_version, schema_version, created_by)
VALUES (2, 2, '{"version":"1684149744","scenario_id":"2","scenario_title":"4xx Error","scenario_type":"SYSTEM","enabled":true,"workloads":{"bf4e5f9e-2ac9-59fa-aa69-1a2ceecda565":{"executor":"OTEL","service":"*/*","trace_role":"server","protocol":"HTTP","rule":{"type":"rule_group","condition":"AND","rules":[{"type":"rule","id":"\"attributes\".\"http.status_code\"","field":"Response Status","datatype":"integer","input":"integer","operator":"greater_than","value":"399"},{"type":"rule","id":"\"attributes\".\"http.status_code\"","field":"Response Status","datatype":"integer","input":"integer","operator":"less_than","value":"500"}]}}},"filter":{"type":"workload","condition":"AND","workload_ids":["bf4e5f9e-2ac9-59fa-aa69-1a2ceecda565"]},"group_by":[{"workload_id":"bf4e5f9e-2ac9-59fa-aa69-1a2ceecda565","title":"#getWorkloadFromIP(SourceIP)","hash":"#getWorkloadFromIP(SourceIP)"},{"workload_id":"bf4e5f9e-2ac9-59fa-aa69-1a2ceecda565","title":"\"attributes\".\"http.status_code\"","hash":"\"attributes\".\"http.status_code\""}],"rate_limit":[{"bucket_max_size":5,"bucket_refill_size":5,"tick_duration":"1m"}]}', 1693843788, 'v1', 'SYSTEM');

INSERT INTO scenario_version (scenario_version_id, scenario_id, scenario_data, scenario_version, schema_version, created_by)
VALUES (3, 3, '{"version":"1684149744","scenario_id":"3","scenario_title":"5xx Error","scenario_type":"SYSTEM","enabled":true,"workloads":{"4b8faded-e3b9-5ff7-a097-d0efca722449":{"executor":"OTEL","service":"*/*","trace_role":"server","protocol":"HTTP","rule":{"type":"rule_group","condition":"AND","rules":[{"type":"rule","id":"\"attributes\".\"http.status_code\"","field":"Response Status","datatype":"integer","input":"integer","operator":"greater_than","value":"499"}]}}},"filter":{"type":"workload","condition":"AND","workload_ids":["4b8faded-e3b9-5ff7-a097-d0efca722449"]},"group_by":[{"workload_id":"4b8faded-e3b9-5ff7-a097-d0efca722449","title":"#getWorkloadFromIP(DestinationIP)","hash":"#getWorkloadFromIP(DestinationIP)"},{"workload_id":"4b8faded-e3b9-5ff7-a097-d0efca722449","title":"\"attributes\".\"http.status_code\"","hash":"\"attributes\".\"http.status_code\""}],"rate_limit":[{"bucket_max_size":5,"bucket_refill_size":5,"tick_duration":"1m"}]}', 1693843788, 'v1', 'SYSTEM');

INSERT INTO scenario_version (scenario_version_id, scenario_id, scenario_data, scenario_version, schema_version, created_by)
VALUES (4, 4, '{"version":"1684149744","scenario_id":"4","scenario_title":"Requests with latency > 100ms","scenario_type":"SYSTEM","enabled":true,"workloads":{"4d073ce7-9cc3-5fcf-a0e1-aa50218088cc":{"executor":"OTEL","service":"*/*","trace_role":"server","protocol":"HTTP","rule":{"type":"rule_group","condition":"AND","rules":[{"type":"rule","id":"latency_ns","field":"Latency (ns)","datatype":"integer","input":"integer","operator":"greater_than","value":"100000000"}]}}},"filter":{"type":"workload","condition":"AND","workload_ids":["4d073ce7-9cc3-5fcf-a0e1-aa50218088cc"]},"group_by":[{"workload_id":"4d073ce7-9cc3-5fcf-a0e1-aa50218088cc","title":"#getWorkloadFromIP(DestinationIP)","hash":"#getWorkloadFromIP(DestinationIP)"}],"rate_limit":[{"bucket_max_size":5,"bucket_refill_size":5,"tick_duration":"1m"}]}', 1693843788, 'v1', 'SYSTEM');
