// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	scenarioResponseModel "zk-api-server/app/scenario/model"
	repository "zk-api-server/app/scenario/repository"

	mock "github.com/stretchr/testify/mock"
)

// ScenarioRepo is an autogenerated mock type for the ScenarioRepo type
type ScenarioRepo struct {
	mock.Mock
}

// GetAllScenario provides a mock function with given fields: filters
func (_m *ScenarioRepo) GetAllScenario(filters *repository.ScenarioQueryFilter) (*[]scenarioResponseModel.ScenarioDbResponse, error) {
	ret := _m.Called(filters)
	return ret.Get(0).(*[]scenarioResponseModel.ScenarioDbResponse), ret.Get(1).(error)
}

type mockConstructorTestingTNewScenarioRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewScenarioRepo creates a new instance of ScenarioRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScenarioRepo() *ScenarioRepo {
	return &ScenarioRepo{}
}
