// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	context "github.com/kataras/iris/v12/context"

	mock "github.com/stretchr/testify/mock"
)

// ClusterHandler is an autogenerated mock type for the ClusterHandler type
type ClusterHandler struct {
	mock.Mock
}

// DeleteCluster provides a mock function with given fields: ctx
func (_m *ClusterHandler) DeleteCluster(ctx *context.Context) {
	_m.Called(ctx)
}

// GetPodDetails provides a mock function with given fields: ctx
func (_m *ClusterHandler) GetPodDetails(ctx *context.Context) {
	_m.Called(ctx)
}

// GetPodList provides a mock function with given fields: ctx
func (_m *ClusterHandler) GetPodList(ctx *context.Context) {
	_m.Called(ctx)
}

// GetPxData provides a mock function with given fields: ctx
func (_m *ClusterHandler) GetPxData(ctx *context.Context) {
	_m.Called(ctx)
}

// GetResourceDetailsList provides a mock function with given fields: ctx
func (_m *ClusterHandler) GetResourceDetailsList(ctx *context.Context) {
	_m.Called(ctx)
}

// GetResourceDetailsMap provides a mock function with given fields: ctx
func (_m *ClusterHandler) GetResourceDetailsMap(ctx *context.Context) {
	_m.Called(ctx)
}

// GetServiceDetails provides a mock function with given fields: ctx
func (_m *ClusterHandler) GetServiceDetails(ctx *context.Context) {
	_m.Called(ctx)
}

// UpsertCluster provides a mock function with given fields: ctx
func (_m *ClusterHandler) UpsertCluster(ctx *context.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewClusterHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterHandler creates a new instance of ClusterHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterHandler(t mockConstructorTestingTNewClusterHandler) *ClusterHandler {
	mock := &ClusterHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
