// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ItemType is an autogenerated mock type for the ItemType type
type ItemType struct {
	mock.Mock
}

type mockConstructorTestingTNewItemType interface {
	mock.TestingT
	Cleanup(func())
}

// NewItemType creates a new instance of ItemType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewItemType(t mockConstructorTestingTNewItemType) *ItemType {
	mock := &ItemType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
