// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplateruleengine = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/o/cluster/rules": {
            "get": {
                "description": "Returns all the Scenario",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Returns all the Scenario",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.ZkHttpResponse-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.ZkHttpError": {
            "type": "object",
            "properties": {
                "info": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "kind": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "param": {
                    "type": "string"
                },
                "stack": {}
            }
        },
        "utils.ZkHttpResponse-string": {
            "type": "object",
            "properties": {
                "debug": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "error": {
                    "$ref": "#/definitions/utils.ZkHttpError"
                },
                "message": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInforuleengine holds exported Swagger Info so clients can modify it
var SwaggerInforuleengine = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "scenario",
	SwaggerTemplate:  docTemplateruleengine,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInforuleengine.InstanceName(), SwaggerInforuleengine)
}
