definitions:
  utils.ZkHttpError:
    properties:
      info:
        additionalProperties: {}
        type: object
      kind:
        type: string
      message:
        type: string
      param:
        type: string
      stack: {}
    type: object
  utils.ZkHttpResponse-string:
    properties:
      debug:
        additionalProperties: {}
        type: object
      error:
        $ref: '#/definitions/utils.ZkHttpError'
      message:
        type: string
      payload:
        type: string
    type: object
info:
  contact: {}
paths:
  /o/cluster/rules:
    get:
      description: Returns all the Rules
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ZkHttpResponse-string'
      summary: Returns all the Rules
      tags:
      - rules
swagger: "2.0"
