apiVersion: v1
data:
  cluster.conf: |-
    {
        "Domain": "px.{{ .Values.global.zkcloud.host }}:443",
        "Url": "{{ .Values.app.url }}"
    }
kind: ConfigMap
metadata:
  name: zk-api-server-config
