apiVersion: v1
data:
  config.yaml: |-
    server:
      host: localhost
      port: 80

    logs:
      color: true
      level: DEBUG

    http:
      debug: true

    postgres:
      host: "{{ .Values.postgres.host }}"
      port: {{ .Values.postgres.port }}
      user: "{{ .Values.postgres.user }}"
      password: ""
      dbname: "{{ .Values.postgres.database }}"
kind: ConfigMap
metadata:
  name: {{ include "zk-api-server.fullname" . }}
