apiVersion: batch/v1
kind: Job
metadata:
  name: "zk-api-server-migration"
  namespace: "zkcloud"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  completions: 1
  template:
    spec:
      restartPolicy: {{ .Values.image.migrationRestartPolicy }}
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: migration
          image: "{{ .Values.global.dockerBase }}/{{ .Values.image.migrationRepo }}:{{ .Values.image.migrationTag  }}"
          command: [ "/bin/sh", "-c", "migrate -path=/zk/migrations -database=postgres://$PL_POSTGRES_USERNAME:$PL_POSTGRES_PASSWORD@{{ .Values.postgres.host }}:5432/{{ .Values.postgres.database }}?sslmode=disable\\&x-migrations-table=zk_api_server_migrations up" ]
          env:
            - name: PL_POSTGRES_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: pl-db-secrets
                  key: PL_POSTGRES_USERNAME

            - name: PL_POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: pl-db-secrets
                  key: PL_POSTGRES_PASSWORD
