server:
  host: localhost
  port: 80

logs:
  color: true
  level: DEBUG

http:
  debug: true

postgres:
  host: postgres.zkcloud.svc.cluster.local
  port: 5432
  user: "postgres"
  password: "0kP@ssw0rD"
  dbname: "zk"
