apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: zkcloud
  labels:
    app: api-server
spec:
  selector:
    app: api-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
