name: CICD
on:
  workflow_dispatch:
     inputs:
        ENV:
            description: 'ENV'
            required: true
            default: 'poc'
env:
  NS: ${{ vars.NS }}
  ENV: ${{ github.event.inputs.ENV }}
  GOOS: ${{ vars.GOOS }}
  GOARCH: ${{ vars.GOARCH }}
  CGO_ENABLED: ${{ vars.CGO_ENABLED }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  DOMAIN: ${{ vars.DOMAIN }}
  URL: ${{ vars.URL }}
  
jobs:
  build:
    environment: ${{ github.event.inputs.ENV }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
    
      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -o main main.go
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'
        

      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: latest
          export_default_credentials: true
      - name: login to docker registry
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
           cluster_name: '${{ env.GKE_CLUSTER }}'
           location: '${{ env.GKE_ZONE }}'

      - name: Docker build
        run: |-
            docker build  --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA" .
      
      - name: Docker push
        run: |-
            docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA"
   
      
      - name: Set up helm
        run: |-
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
  

      - name: Deploy
        run: |-
             helm --install  \
             --set=image.repository=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME \
             --set=image.tag=$GITHUB_SHA \
             --set=app.DOMAIN=$DOMAIN \
             --set=app.URL=$URL \
             upgrade $APP_NAME \
              -f ./helm-charts/$ENV.yaml ./helm-charts/ \
              --namespace $NS 
