name: CICD (zk-runner)
on:
  workflow_dispatch:
     inputs:
        ENV:
            description: 'ENV'
            required: true
            default: 'poc'
        DOCKER_TAG:
            description: 'Docker Image Tag'
            required: true
            default: 'latest'
        GKE_CLUSTER:
            description: 'Cluster Name'
            required: true
            default: 'pxclient01'
        BUILD_AND_PUSH:
          type: boolean
          default: true
          description: Build and Push?
        DEPLOY:
          type: boolean
          description: Deploy?
env:
  NS: ${{ vars.NS }}
  ENV: ${{ github.event.inputs.ENV }}
  DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
  GOOS: ${{ vars.GOOS }}
  GOARCH: ${{ vars.GOARCH }}
  CGO_ENABLED: ${{ vars.CGO_ENABLED }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ github.event.inputs.GKE_CLUSTER }}
  GKE_ZONE : ${{ vars.GKE_ZONE }}
  DOCKER_REG: ${{ vars.DOCKER_REG }}
  PROJECT_ID:  ${{ vars.PROJECT_ID }}
  DOCKER_REPO:  ${{ vars.DOCKER_REPO }}
  APP_NAME:  ${{ vars.APP_NAME }}
  DOMAIN: ${{ vars.DOMAIN }}
  URL: ${{ vars.URL }}
  GOPRIVATE : ${{ vars.GOPRIVATE }}
  TOKEN: ${{ secrets.GITPAT }}
  BUILD_AND_PUSH: ${{ github.event.inputs.BUILD_AND_PUSH }}
  DEPLOY: ${{ github.event.inputs.DEPLOY }}

jobs:
  app-build:
    environment: ${{ github.event.inputs.ENV }}
    runs-on: zk-self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure git for private modules
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        run: | 
          git config --global url."https://$TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          cat ~/.gitconfig

      - name: Build
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        run: go build -o main main.go

      - name: Uploading Helm Charts (for deploy)
        uses: actions/upload-artifact@v3
        if: ${{ env.DEPLOY == 'true' }}
        with:
          name: helm-charts
          path: |
            helm-charts
      - name: Uploading Build files (for docker push)
        uses: actions/upload-artifact@v3
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        with:
          name: build-artifacts
          path: |
            app/px/
            main
            internal/config/config.yaml
            data.json
            Dockerfile
        
  docker-build:
    needs: app-build
    environment: ${{ github.event.inputs.ENV }}
    runs-on: zk-self-hosted
    steps:
      - id: 'auth'
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'
      - name: login to docker registry
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        run: |
          gcloud auth configure-docker $DOCKER_REG --quiet

      - id: 'get-credentials'
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
           cluster_name: '${{ env.GKE_CLUSTER }}'
           location: '${{ env.GKE_ZONE }}'
      - uses: actions/download-artifact@v3
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        with:
          name: build-artifacts
      - name: Docker build
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        run: |-
            docker build  --tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA" .
     
      - name: Docker Tag
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        run: |-
            docker tag "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA" "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$DOCKER_TAG"
           
      - name: Docker push
        if: ${{ env.BUILD_AND_PUSH == 'true' }}
        run: |-
            docker push "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$GITHUB_SHA"
            docker push  "$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME:$DOCKER_TAG" 
  deploy:
    needs: [app-build,docker-build]
    environment: ${{ github.event.inputs.ENV }}
    runs-on: zk-self-hosted
    steps:  
      - id: 'auth'
        if: ${{ env.DEPLOY == 'true' }}
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'
      - id: 'get-credentials'
        if: ${{ env.DEPLOY == 'true' }}
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
           cluster_name: '${{ env.GKE_CLUSTER }}'
           location: '${{ env.GKE_ZONE }}'
      - uses: actions/download-artifact@v3
        if: ${{ env.DEPLOY == 'true' }}
        with:
          name: helm-charts

      - name: Deploy
        if: ${{ env.DEPLOY == 'true' }}
        run: |-
             helm --install  \
             --set=image.repository=$DOCKER_REG/$PROJECT_ID/$DOCKER_REPO/$APP_NAME \
             --set=image.tag=$DOCKER_TAG \
             --set=app.DOMAIN=$DOMAIN \
             --set=app.URL=$URL \
             upgrade $APP_NAME \
              -f $ENV.yaml ./ \
              --create-namespace \
              --namespace $NS
